# Generated by Django 3.1.5 on 2021-04-04 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date/Time')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('workout_type', models.CharField(blank=True, max_length=50, verbose_name='Type of Workout')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories Burned')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
