# Generated by Django 3.1.5 on 2021-04-04 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
                ('streak', models.IntegerField(default=0, verbose_name='Streak')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
