# Generated by Django 3.1.5 on 2021-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='max_exp',
            field=models.IntegerField(default=1000, verbose_name='Progress'),
        ),
    ]
