# Generated by Django 3.1.5 on 2021-04-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_dashboard_max_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='progressTotal',
            field=models.IntegerField(default=0, verbose_name='ProgressTotal'),
        ),
    ]
