# Generated by Django 3.1.5 on 2021-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_dashboard_progresstotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Progress'),
        ),
    ]
