# Generated by Django 3.1.5 on 2021-04-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_dashboard_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
