# Generated by Django 3.1.5 on 2021-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20210413_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='max_exp',
            field=models.IntegerField(default=200, verbose_name='Progress'),
        ),
    ]
